version: '2'
services:
  mqtestproducer-app:
    image: mqtestproducer
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://mqtestproducer-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=mqTestProducer
      - JHIPSTER_CACHE_REDIS_SERVER=redis://mqtestproducer-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://mqtestproducer-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://mqtestproducer-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://mqtestproducer-elasticsearch:9200
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - 8080:8080
  mqtestproducer-mongodb:
    extends:
      file: mongodb.yml
      service: mqtestproducer-mongodb
  mqtestproducer-redis:
    extends:
      file: redis.yml
      service: mqtestproducer-redis
  mqtestproducer-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: mqtestproducer-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
